<a href="https://colab.research.google.com/github/DavideMichelon10/CV-DP-refresh/blob/main/Feed_forward_propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
def tanh(x):
  return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))
def relu(x):
  return np.where(x>0, x, 0)
def linear(x):
  return x

In [59]:
def feed_forward(inputs, outputs, weights):
  pre_hidden = np.dot(inputs, weights[0]) + weights[1]
  hidden =  1 / (1 + np.exp(-pre_hidden)) # sigmoid
  pred_out = np.dot(hidden, weights[2]) + weights[3]
  mean_squared_error = np.mean(np.square(outputs - pred_out))
  return mean_squared_error

In [10]:
def softmax(x: list): #ritorna un probability vector
  return np.exp(x) / np.sum (np.exp(x))

array([0.00606817, 0.33131061, 0.33131061, 0.33131061])

## Loss functions

In [11]:
# variabili continue
def mse(outputs, y): # (output - y)^2
  return np.mean(np.square(outputs - y))
def mae(outputs, y): # |output - y|
  return np.mean(np.abs(outputs - y))

In [ ]:
# variabili categoriche
def binary_cross_entropy(outputs, y): # [1,1,1,0,1,0,0, ... ]
  return - np.mean(y * np.log(outputs) + (1-y) * np.log(1-outputs))

def categorical_cross_entropy(outputs, y):
  return - np.mean(np.log(outputs[np.arange(len(y)), y]))

## Gradient descent

In [54]:
from copy import deepcopy

In [92]:
def update_weights(inputs, outputs, weights, lr):
    original_weights = deepcopy(weights)
    temp_weights = deepcopy(weights)
    updated_weights = deepcopy(weights)
    original_loss = feed_forward(inputs, outputs, original_weights)

    for i, layer in enumerate(original_weights):
        for index, weight in np.ndenumerate(layer):
            temp_weights = deepcopy(weights)
            temp_weights[i][index] += lr
            _loss_plus = feed_forward(inputs, outputs, temp_weights)
            grad = (_loss_plus - original_loss)/ lr
            updated_weights[i][index] -= grad*lr
            print(f"original_loss: {original_loss} _loss_plus: {_loss_plus} grad: {grad}")
    return updated_weights, original_loss

In [93]:
x = np.array([[1,1]])
y = np.array([[0]])
weights = [
    np.array([[-0.0053, 0.3793],
              [-0.5820, -0.5204],
              [-0.2723, 0.1896]], dtype=np.float32).T,
    np.array([-0.0140, 0.5607, -0.0628], dtype=np.float32),
    np.array([[ 0.1528, -0.1745, -0.1135]], dtype=np.float32).T,
    np.array([-0.5516], dtype=np.float32)
]
update_weights(x, y, weights, 0.001)

original_loss: 0.33455008989960927 _loss_plus: 0.33450730647047366 grad: -0.04278342913560662
original_loss: 0.33455008989960927 _loss_plus: 0.33459703447394723 grad: 0.04694457433795929
original_loss: 0.33455008989960927 _loss_plus: 0.33458274271782396 grad: 0.032652818214684576
original_loss: 0.33455008989960927 _loss_plus: 0.3345073070282384 grad: -0.042782871370883324
original_loss: 0.33455008989960927 _loss_plus: 0.33459703447394723 grad: 0.04694457433795929
original_loss: 0.33455008989960927 _loss_plus: 0.3345827432044245 grad: 0.03265330481522222
original_loss: 0.33455008989960927 _loss_plus: 0.33450730647047366 grad: -0.04278342913560662
original_loss: 0.33455008989960927 _loss_plus: 0.33459703447394723 grad: 0.04694457433795929
original_loss: 0.33455008989960927 _loss_plus: 0.33458274308277436 grad: 0.03265318316508781
original_loss: 0.33455008989960927 _loss_plus: 0.33386902992035183 grad: -0.6810599792574368
original_loss: 0.33455008989960927 _loss_plus: 0.33412476004015845 

([array([[-0.00525722, -0.582047  , -0.27233267],
         [ 0.3793428 , -0.52044696,  0.18956736]], dtype=float32),
  array([-0.01395722,  0.56065303, -0.06283265], dtype=float32),
  array([[ 0.15348105],
         [-0.17407468],
         [-0.11296382]], dtype=float32),
  array([-0.5504442], dtype=float32)],
 np.float64(0.33455008989960927))

## Backpropagation